export const config = {
  Backquote: { en: ['`', '~'], ru: 'ё' },
  Backslash: { en: ['\\', '|'], ru: ['\\', '/'] },
  BracketLeft: { en: ['[', '{'], ru: 'х' },
  BracketRight: { en: [']', '}'], ru: 'ъ' },
  Comma: { en: [',', '<'], ru: ['б', 'Б'] },
  Digit0: { en: ['0', ')'], ru: ['0', ')'] },
  Digit1: { en: ['1', '!'], ru: ['1', '!'] },
  Digit2: { en: ['2', '@'], ru: ['2', '"'] },
  Digit3: { en: ['3', '#'], ru: ['3', '№'] },
  Digit4: { en: ['4', '$'], ru: ['4', ';'] },
  Digit5: { en: ['5', '%'], ru: ['5', '%'] },
  Digit6: { en: ['6', '^'], ru: ['6', ':'] },
  Digit7: { en: ['7', '&'], ru: ['7', '?'] },
  Digit8: { en: ['8', '*'], ru: ['8', '*'] },
  Digit9: { en: ['9', '('], ru: ['9', '('] },
  Equal: { en: ['=', '+'], ru: ['=', '+'] },
  KeyA: { en: 'a', ru: 'ф' },
  KeyB: { en: 'b', ru: 'и' },
  KeyC: { en: 'c', ru: 'с' },
  KeyD: { en: 'd', ru: 'в' },
  KeyE: { en: 'e', ru: 'у' },
  KeyF: { en: 'f', ru: 'а' },
  KeyG: { en: 'g', ru: 'п' },
  KeyH: { en: 'h', ru: 'р' },
  KeyI: { en: 'i', ru: 'ш' },
  KeyJ: { en: 'j', ru: 'о' },
  KeyK: { en: 'k', ru: 'л' },
  KeyL: { en: 'l', ru: 'д' },
  KeyM: { en: 'm', ru: 'ь' },
  KeyN: { en: 'n', ru: 'т' },
  KeyO: { en: 'o', ru: 'щ' },
  KeyP: { en: 'p', ru: 'з' },
  KeyQ: { en: 'q', ru: 'й' },
  KeyR: { en: 'r', ru: 'к' },
  KeyS: { en: 's', ru: 'ы' },
  KeyT: { en: 't', ru: 'е' },
  KeyU: { en: 'u', ru: 'г' },
  KeyV: { en: 'v', ru: 'м' },
  KeyW: { en: 'w', ru: 'ц' },
  KeyX: { en: 'x', ru: 'ч' },
  KeyY: { en: 'y', ru: 'н' },
  KeyZ: { en: 'z', ru: 'я' },
  Period: { en: ['.', '>'], ru: 'ю' },
  Quote: { en: ['\'', '"'], ru: 'э' },
  Semicolon: { en: [';', ':'], ru: 'ж' },
  Minus: { en: ['-', '_'], ru: ['-', '_'] },
  Slash: { en: ['/', '?'], ru: ['.', ','] },
  Space: { en: ' ', ru: ' ', special: true },
  AltLeft: { en: 'Alt', ru: 'Alt', special: true },
  AltRight: { en: 'Alt', ru: 'Alt', special: true },
  ArrowDown: { en: '∨', ru: '∨', special: true },
  ArrowLeft: { en: '<', ru: '<', special: true },
  ArrowRight: { en: '>', ru: '>', special: true },
  ArrowUp: { en: '∧', ru: '∧', special: true },
  Backspace: { en: 'Backspace', ru: 'Backspace', special: true },
  CapsLock: { en: 'Caps Lock', ru: 'Caps Lock', special: true },
  ControlLeft: { en: 'Ctrl', ru: 'Ctrl', special: true },
  ControlRight: { en: 'Ctrl', ru: 'Ctrl', special: true },
  Delete: { en: 'DEL', ru: 'DEL', special: true },
  Enter: { en: 'Enter', ru: 'Enter', special: true },
  MetaLeft: { en: 'Win', ru: 'Win', special: true },
  Shift: { en: 'Shift', ru: 'Shift', special: true },
  Tab: { en: 'Tab', ru: 'Tab', special: true }
};

export const layout = [
  ['Backquote', 'Digit1', 'Digit2', 'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7', 'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal', ['Backspace', 2]],
  [['Tab', 2], 'KeyQ', 'KeyW', 'KeyE', 'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO', 'KeyP', 'BracketLeft', 'BracketRight', 'Backslash'],
  [['CapsLock', 2], 'KeyA', 'KeyS', 'KeyD', 'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL', 'Semicolon', 'Quote', ['Enter', 2]],
  [['Shift', 2], 'KeyZ', 'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM', 'Comma', 'Period', 'Slash', 'ArrowUp', 'Delete'],
  [['ControlLeft', 2], ['MetaLeft', 1.5], ['AltLeft', 1.5], ['Space', 3.35], ['AltRight', 1.5], ['ControlRight', 1.5], 'ArrowLeft', 'ArrowDown', 'ArrowRight']
];

export const defaultValues = {
  buttonMinWidth: 10,
  buttonWidth: 4,
  lang: 'en',
  altLang: 'ru'
};
